pipeline{

    agent any

    stages {

        stage ('Compile Stage') {

            steps {

                withMaven(maven: 'maven_3_5_0') {
                    sh 'mvn clean install'

                }

            }
        }
         stage('SonarQube'){
        		steps{
        				bat label: '', script: '''mvn sonar:sonar \
        				-Dsonar.host.url=http://localhost:9000 \
        				-Dsonar.login=squ_b89b23e99afd0e03b0a56f6d924b36f377c56334'''
        			}
           		}
    stage ('Test Stage') {

            steps {

                withMaven(maven: 'maven_3_5_0') {
                    sh 'mvn test'

                }

            }
        }


        stage ('Cucumber Reports') {

            steps {
                cucumber buildStatus: "UNSTABLE",
                    fileIncludePattern: "**/cucumber.json",
                    jsonReportDirectory: 'target'

            }

        }

    }

}